### ISSUE TITLE
Accelerometer stops working after random amount of time.

### ISSUE THREAD

**Issue by nuket** [Seeed-Studio/Accelerometer_MMA7660#1]
Unsure why this is the case. Even if I am moving the Accelerometer around such that it has no reason to go to sleep, the output stops after a random amount of time. Currently the sensor is attached to an Arduino Nano.

See:
- https://vilimpoc.org/media/grove-freeze-1.mp4
- https://vilimpoc.org/media/grove-freeze-2.mp4
- https://vilimpoc.org/media/grove-freeze-3.mp4

**Comment by awong1900** [comment]
Any code with gits?

**Comment by nuket** [comment]
Hi, I was using only the provided MMA7660 example code in my sketch. I have 
not had a chance to track down which function hangs in the MMA7660 library, 
but I'm pushing all changes to my fork.

**Comment by JimmyBillan** [comment]
Hi nuket, thank you for the fix. No memory leak anymore, but you should remove the debug code so anyone can download the zip and make it work without problem :)
