### ISSUE TITLE
Issues with Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Accelerometer_MMA7660#3]
In the file MMA7660.cpp there are a number of issues with Wire.requestFrom().

The Wire.requestFrom() should not have Wire.beginTransmission() or Wire.endTransmission(). 
This in in the funtion MMA7660::read.

There is no need to empty a buffer or stream before using Wire.requestFrom(). When the Wire.requestFrom() returns, the receive buffer in the Wire library does not contain old data.
This is in the function MMA7660::getXYZ, MMA7660::getAcceleration, MMA7660::getAllData.

There is no need for a timeout. The Wire.requestFrom() waits until the complete I2C transaction has finished. The Wire.read() after that, only reads data from a receive buffer in the Wire library.
This is in the function MMA7660:getXYZ, MMA7660:getAcceleration,.

**Comment by KillingJacky** [comment]
Hi @Koepel , thanks for your percipience. If you like, could you please commit your patch for this driver with a pull-request? That prevents us reinvent the wheel and would be pretty appreciated.

**Comment by Koepel** [comment]
@KillingJacky, At this moment I hope that Seeed-Studio will use the Arduino Wire library in the way it is meant to be. When a library needs to be changed, the Wire library issue could be solved as well.

On the Arduino forums I'm seeing the wrong use of the Wire library so many times. That is why I made the issues here on Github.

I learned yesterday that and old Arduino Zero Wire library did indeed keep previous data in the Wire receive buffer. But that was a serious bug, and it should be fixed with version Arduino.cc IDE 1.6.8.

In the code is a "Wire.begin()" in the "read()" and "write()" function. At this moment it is allowed to call Wire.begin() multiple times, but that is a lot of extra unnecessary code. I would like to change that as well, but I don't have a MMA7660 to test new code.

**Comment by KillingJacky** [comment]
Hi @Koepel thank you very much for your precise thought. After I studied those libraries you pointed out, yes we had misunderstanding about the usage of the Wire library. As those libraries are working fine in the field currently, we will continuously spend our efforts to fix those mis-uses.

**Comment by ackPeng** [comment]
Thank you very much, I will closing this issue, If you have any further problem. Please reopen it or create a new one
