### ISSUE TITLE
Interrupt Trigger

### ISSUE THREAD

**Issue by Bedhead8** [Seeed-Studio/Accelerometer_MMA7660#5]
This is a Fantastic library for the MMA7660.   I was attempting to enable the interrupts Register but was having Difficulty setting that by the Wire LIB.  Is there a function that can change the interrupt Register to trigger a 1 for the various trigger modes.

Orientation Change                               When                           FBINT, PLINT = 1
Shake                                                     When                           SHINTX, SHINTY, SHINTZ = 1
Tap or Tilt                                              When                           PDINT = 1
Auto-Wake/Sleep                                  When                           ASINT = 1
X, Y, Z Data Update                                When                          GINT = 1

**Comment by LabAbertoFabLab** [comment]
Hello, how can we have this X, Y, Z Data Update When GINT = 1? If this register is enable we have real-time tracking motion. Best. António

**Comment by ackPeng** [comment]
I'm very sorry that this library has not yet written an interface related to directly setting interrupt registers.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
